# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 277fb347f6be97591b920ecf70c94dc8343d374c6f1eca3b8f351139361086bf9bbe07c349b5479c1307596220e3054da63cfd63bbe727df724da31b7d2d79a8

test:
  secret_key_base: e9d54a1766d13caee5fc7e78a7a6ce421c498052e60cd3cb4f17fe50ae98dbd0156c659b00f879a9c7d6db0c037ae4681b91b327727a19eba565d18e7c243595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
